version: '3.3'
services:
  mariadb:
    container_name: "mariadb" 
    build:
      context: ./mariadb
      args :
        - data_name=wordpress
        - USER=achraf
        - PASSWORD=123
    env_file:
      - ./var.env
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - net
  wordpress:
    container_name: "wordpress" 
    build:
      context: ./wordpress
      args :
        - data_name=wordpress
        - USER=achraf
        - PASSWORD=123
        - DOMAIN_NAME=ael-kouc.42.fr
        - TITLE=hellow_word
        - ADMIN_U=ana
        - ADMIN_MAIL=achraf.miam@gmail.com
        - WP_USR=achraf2
        - WP_EMAIL=ael-kouc@student.1337.ma
    env_file:
      - ./var.env
    volumes:
      - wp:/var/www/html
    networks:
      - net
    depends_on:
      - mariadb
  ngnix:
    container_name: "ngnix" 
    build:
      context: ./ngnix
    volumes:
      - wp:/var/www/html
    networks:
      - net
    depends_on:
      - wordpress
    ports:
      - 443:443
networks:
  net:
    name: "net"
    driver: "bridge"
volumes:
  dbdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ael-kouc/data/db
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ael-kouc/data/wp

